# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  ljtrtool.twig.extension.todo:
      class: LJTrTool\RegistrationBundle\Twig\Extension\TodoExtension
      arguments:
        doctrine: "@doctrine"
      tags:
        - { name: twig.extension }


#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
