<?php

namespace Proxies\__CG__\LJTrTool\RegistrationBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TodoCategory extends \LJTrTool\RegistrationBundle\Entity\TodoCategory implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\TodoCategory' . "\0" . 'todoCategoryId', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\TodoCategory' . "\0" . 'todoCategoryName', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\TodoCategory' . "\0" . 'todos');
        }

        return array('__isInitialized__', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\TodoCategory' . "\0" . 'todoCategoryId', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\TodoCategory' . "\0" . 'todoCategoryName', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\TodoCategory' . "\0" . 'todos');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TodoCategory $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function addTodo(\LJTrTool\RegistrationBundle\Entity\Todo $todo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTodo', array($todo));

        return parent::addTodo($todo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTodoCategoryId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getTodoCategoryId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTodoCategoryId', array());

        return parent::getTodoCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTodoCategoryName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTodoCategoryName', array());

        return parent::getTodoCategoryName();
    }

    /**
     * {@inheritDoc}
     */
    public function getTodos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTodos', array());

        return parent::getTodos();
    }

    /**
     * {@inheritDoc}
     */
    public function removeTodo(\LJTrTool\RegistrationBundle\Entity\Todo $todo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTodo', array($todo));

        return parent::removeTodo($todo);
    }

    /**
     * {@inheritDoc}
     */
    public function setTodoCategoryId($todoCategoryId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTodoCategoryId', array($todoCategoryId));

        return parent::setTodoCategoryId($todoCategoryId);
    }

    /**
     * {@inheritDoc}
     */
    public function setTodoCategoryName($todoCategoryName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTodoCategoryName', array($todoCategoryName));

        return parent::setTodoCategoryName($todoCategoryName);
    }

    /**
     * {@inheritDoc}
     */
    public function setTodos($todos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTodos', array($todos));

        return parent::setTodos($todos);
    }

}
