<?php

namespace Proxies\__CG__\LJTrTool\RegistrationBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Division extends \LJTrTool\RegistrationBundle\Entity\Division implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Division' . "\0" . 'divisionId', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Division' . "\0" . 'divisionName', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Division' . "\0" . 'persons', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Division' . "\0" . 'approvals');
        }

        return array('__isInitialized__', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Division' . "\0" . 'divisionId', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Division' . "\0" . 'divisionName', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Division' . "\0" . 'persons', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Division' . "\0" . 'approvals');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Division $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function addPerson(\LJTrTool\RegistrationBundle\Entity\Person $person)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPerson', array($person));

        return parent::addPerson($person);
    }

    /**
     * {@inheritDoc}
     */
    public function addApproval(\LJTrTool\RegistrationBundle\Entity\DivisionApproval $approval)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addApproval', array($approval));

        return parent::addApproval($approval);
    }

    /**
     * {@inheritDoc}
     */
    public function getDivisionId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getDivisionId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDivisionId', array());

        return parent::getDivisionId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDivisionName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDivisionName', array());

        return parent::getDivisionName();
    }

    /**
     * {@inheritDoc}
     */
    public function getPersons()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersons', array());

        return parent::getPersons();
    }

    /**
     * {@inheritDoc}
     */
    public function getApprovals()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApprovals', array());

        return parent::getApprovals();
    }

    /**
     * {@inheritDoc}
     */
    public function removePerson(\LJTrTool\RegistrationBundle\Entity\Person $person)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePerson', array($person));

        return parent::removePerson($person);
    }

    /**
     * {@inheritDoc}
     */
    public function removeApproval(\LJTrTool\RegistrationBundle\Entity\DivisionApproval $approval)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeApproval', array($approval));

        return parent::removeApproval($approval);
    }

    /**
     * {@inheritDoc}
     */
    public function setApprovals($approvals)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApprovals', array($approvals));

        return parent::setApprovals($approvals);
    }

    /**
     * {@inheritDoc}
     */
    public function setDivisionId($divisionId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDivisionId', array($divisionId));

        return parent::setDivisionId($divisionId);
    }

    /**
     * {@inheritDoc}
     */
    public function setDivisionName($divisionName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDivisionName', array($divisionName));

        return parent::setDivisionName($divisionName);
    }

    /**
     * {@inheritDoc}
     */
    public function setPersons($persons)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersons', array($persons));

        return parent::setPersons($persons);
    }

}
