<?php

namespace Proxies\__CG__\LJTrTool\RegistrationBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Role extends \LJTrTool\RegistrationBundle\Entity\Role implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Role' . "\0" . 'roleId', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Role' . "\0" . 'roleName', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Role' . "\0" . 'displayName', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Role' . "\0" . 'description', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Role' . "\0" . 'conditions', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Role' . "\0" . 'approvals');
        }

        return array('__isInitialized__', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Role' . "\0" . 'roleId', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Role' . "\0" . 'roleName', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Role' . "\0" . 'displayName', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Role' . "\0" . 'description', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Role' . "\0" . 'conditions', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Role' . "\0" . 'approvals');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Role $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function addCondition(\LJTrTool\RegistrationBundle\Entity\Condition $condition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCondition', array($condition));

        return parent::addCondition($condition);
    }

    /**
     * {@inheritDoc}
     */
    public function addApproval(\LJTrTool\RegistrationBundle\Entity\RoleApproval $approval)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addApproval', array($approval));

        return parent::addApproval($approval);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoleId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getRoleId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoleId', array());

        return parent::getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoleName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoleName', array());

        return parent::getRoleName();
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayName', array());

        return parent::getDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    public function getConditions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConditions', array());

        return parent::getConditions();
    }

    /**
     * {@inheritDoc}
     */
    public function getApprovals()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApprovals', array());

        return parent::getApprovals();
    }

    /**
     * {@inheritDoc}
     */
    public function removeCondition(\LJTrTool\RegistrationBundle\Entity\Condition $condition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCondition', array($condition));

        return parent::removeCondition($condition);
    }

    /**
     * {@inheritDoc}
     */
    public function removeApproval(\LJTrTool\RegistrationBundle\Entity\RoleApproval $approval)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeApproval', array($approval));

        return parent::removeApproval($approval);
    }

    /**
     * {@inheritDoc}
     */
    public function setRoleId($roleId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoleId', array($roleId));

        return parent::setRoleId($roleId);
    }

    /**
     * {@inheritDoc}
     */
    public function setRoleName($roleName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoleName', array($roleName));

        return parent::setRoleName($roleName);
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayName($displayName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayName', array($displayName));

        return parent::setDisplayName($displayName);
    }

    /**
     * {@inheritDoc}
     */
    public function setConditions($conditions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConditions', array($conditions));

        return parent::setConditions($conditions);
    }

    /**
     * {@inheritDoc}
     */
    public function setApprovals($approvals)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApprovals', array($approvals));

        return parent::setApprovals($approvals);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function unsetRoleId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unsetRoleId', array());

        return parent::unsetRoleId();
    }

    /**
     * {@inheritDoc}
     */
    public function equals($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'equals', array($role));

        return parent::equals($role);
    }

}
