<?php

namespace Proxies\__CG__\LJTrTool\RegistrationBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Person extends \LJTrTool\RegistrationBundle\Entity\Person implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'personId', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'name', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'firstname', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'email', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'birthday', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'gender', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'phone', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'address', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'division', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'accounts', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'feeding', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'allergies', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'path', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'file', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'temp');
        }

        return array('__isInitialized__', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'personId', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'name', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'firstname', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'email', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'birthday', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'gender', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'phone', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'address', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'division', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'accounts', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'feeding', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'allergies', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'path', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'file', '' . "\0" . 'LJTrTool\\RegistrationBundle\\Entity\\Person' . "\0" . 'temp');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Person $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function addAllergy(\LJTrTool\RegistrationBundle\Entity\Allergy $allergy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAllergy', array($allergy));

        return parent::addAllergy($allergy);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getPersonId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonId', array());

        return parent::getPersonId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', array());

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthday()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthday', array());

        return parent::getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    public function getGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', array());

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', array());

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function getDivision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDivision', array());

        return parent::getDivision();
    }

    /**
     * {@inheritDoc}
     */
    public function getFeeding()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeeding', array());

        return parent::getFeeding();
    }

    /**
     * {@inheritDoc}
     */
    public function getAllergies()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllergies', array());

        return parent::getAllergies();
    }

    /**
     * {@inheritDoc}
     */
    public function removeAllergy(\LJTrTool\RegistrationBundle\Entity\Allergy $allergy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAllergy', array($allergy));

        return parent::removeAllergy($allergy);
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonId($personId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonId', array($personId));

        return parent::setPersonId($personId);
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstname($firstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', array($firstname));

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthday($birthday)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthday', array($birthday));

        return parent::setBirthday($birthday);
    }

    /**
     * {@inheritDoc}
     */
    public function setGender($gender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', array($gender));

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', array($phone));

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function setDivision($division)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDivision', array($division));

        return parent::setDivision($division);
    }

    /**
     * {@inheritDoc}
     */
    public function setFeeding($feeding)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeeding', array($feeding));

        return parent::setFeeding($feeding);
    }

    /**
     * {@inheritDoc}
     */
    public function setAllergies($allergies)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllergies', array($allergies));

        return parent::setAllergies($allergies);
    }

    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', array());

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsolutePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsolutePath', array());

        return parent::getAbsolutePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebPath', array());

        return parent::getWebPath();
    }

    /**
     * {@inheritDoc}
     */
    public function getUploadDir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUploadDir', array());

        return parent::getUploadDir();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile(\Symfony\Component\HttpFoundation\File\UploadedFile $file = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', array($file));

        return parent::setFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function preUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpload', array());

        return parent::preUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function upload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', array());

        return parent::upload();
    }

    /**
     * {@inheritDoc}
     */
    public function storeFilenameForRemove()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'storeFilenameForRemove', array());

        return parent::storeFilenameForRemove();
    }

    /**
     * {@inheritDoc}
     */
    public function removeUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUpload', array());

        return parent::removeUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function setPath($path)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPath', array($path));

        return parent::setPath($path);
    }

    /**
     * {@inheritDoc}
     */
    public function getPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPath', array());

        return parent::getPath();
    }

    /**
     * {@inheritDoc}
     */
    public function getAccounts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccounts', array());

        return parent::getAccounts();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccounts($accounts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccounts', array($accounts));

        return parent::setAccounts($accounts);
    }

    /**
     * {@inheritDoc}
     */
    public function getUniqueName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniqueName', array());

        return parent::getUniqueName();
    }

}
